from enum import Enum


class LogicalTypeRoot(str, Enum):
    ARRAY = "ARRAY"
    BIGINT = "BIGINT"
    BINARY = "BINARY"
    BOOLEAN = "BOOLEAN"
    CHAR = "CHAR"
    DATE = "DATE"
    DECIMAL = "DECIMAL"
    DISTINCT_TYPE = "DISTINCT_TYPE"
    DOUBLE = "DOUBLE"
    FLOAT = "FLOAT"
    INTEGER = "INTEGER"
    INTERVAL_DAY_TIME = "INTERVAL_DAY_TIME"
    INTERVAL_YEAR_MONTH = "INTERVAL_YEAR_MONTH"
    MAP = "MAP"
    MULTISET = "MULTISET"
    NULL = "NULL"
    RAW = "RAW"
    ROW = "ROW"
    SMALLINT = "SMALLINT"
    STRUCTURED_TYPE = "STRUCTURED_TYPE"
    SYMBOL = "SYMBOL"
    TIMESTAMP_WITHOUT_TIME_ZONE = "TIMESTAMP_WITHOUT_TIME_ZONE"
    TIMESTAMP_WITH_LOCAL_TIME_ZONE = "TIMESTAMP_WITH_LOCAL_TIME_ZONE"
    TIMESTAMP_WITH_TIME_ZONE = "TIMESTAMP_WITH_TIME_ZONE"
    TIME_WITHOUT_TIME_ZONE = "TIME_WITHOUT_TIME_ZONE"
    TINYINT = "TINYINT"
    UNRESOLVED = "UNRESOLVED"
    VARBINARY = "VARBINARY"
    VARCHAR = "VARCHAR"

    def __str__(self) -> str:
        return str(self.value)
